### ISSUE TITLE
Config file doesn't get placed into config folder

### ISSUE THREAD

**Issue by djmattyg007** [Lupicus/VendingMachine#2]
A copy of the `vm-server.toml` file doesn't get placed into the `config` folder. This makes it difficult to manage for modpack authors. If a copy of that file is present in the `config` folder, it doesn't seem to get used anyway.

**Comment by Lupicus** [comment]
Server configs don't go in config folder. I'm currently not sure if this is the correct type of config for what I intend, due to the current state of configs, but it seems to work at this time.
For modpack authors, you should be placing this file in defaultconfigs folder, so it places it in every world created.

**Comment by djmattyg007** [comment]
Perhaps it should be a `-common` config file instead of a `-server` config file?

**Comment by Lupicus** [comment]
It could be possible. There seems to be no description on the behavior the different types of config files. The settings are intended for server side, so that was what I choose. When I get a chance I'll look into common.

**Comment by Lupicus** [comment]
I read some about this and it seem that common will probably work.

**Comment by Lupicus** [comment]
The latest version is now in the config folder as a common config.
